PYTHON=python2.7
all:
	echo "type 'make install' as root to install"

install:
	$(PYTHON) setup.py install

clean:
	rm -rf build dparser.pyc tests/d_parser_mach_gen.*

test:
	$(PYTHON) tests/test.py
	$(PYTHON) tests/test2.py
	$(PYTHON) tests/test3.py
	$(PYTHON) tests/test4.py
	$(PYTHON) tests/test5.py
	$(PYTHON) tests/test6.py
	$(PYTHON) tests/test7.py
